package com.tianrui.service.bean.system.base;

import java.util.Date;

public class SystemCodeItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_system_code_item.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_system_code_item.code_id
     *
     * @mbggenerated
     */
    private String codeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_system_code_item.type_value
     *
     * @mbggenerated
     */
    private String typeValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_system_code_item.item_type
     *
     * @mbggenerated
     */
    private Boolean itemType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_system_code_item.digit
     *
     * @mbggenerated
     */
    private String digit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_system_code_item.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_system_code_item.createtime
     *
     * @mbggenerated
     */
    private Long createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_system_code_item.modifier
     *
     * @mbggenerated
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_system_code_item.modifytime
     *
     * @mbggenerated
     */
    private Long modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_system_code_item.utc
     *
     * @mbggenerated
     */
    private Date utc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_system_code_item.id
     *
     * @return the value of tr_system_code_item.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_system_code_item.id
     *
     * @param id the value for tr_system_code_item.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_system_code_item.code_id
     *
     * @return the value of tr_system_code_item.code_id
     *
     * @mbggenerated
     */
    public String getCodeId() {
        return codeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_system_code_item.code_id
     *
     * @param codeId the value for tr_system_code_item.code_id
     *
     * @mbggenerated
     */
    public void setCodeId(String codeId) {
        this.codeId = codeId == null ? null : codeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_system_code_item.type_value
     *
     * @return the value of tr_system_code_item.type_value
     *
     * @mbggenerated
     */
    public String getTypeValue() {
        return typeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_system_code_item.type_value
     *
     * @param typeValue the value for tr_system_code_item.type_value
     *
     * @mbggenerated
     */
    public void setTypeValue(String typeValue) {
        this.typeValue = typeValue == null ? null : typeValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_system_code_item.item_type
     *
     * @return the value of tr_system_code_item.item_type
     *
     * @mbggenerated
     */
    public Boolean getItemType() {
        return itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_system_code_item.item_type
     *
     * @param itemType the value for tr_system_code_item.item_type
     *
     * @mbggenerated
     */
    public void setItemType(Boolean itemType) {
        this.itemType = itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_system_code_item.digit
     *
     * @return the value of tr_system_code_item.digit
     *
     * @mbggenerated
     */
    public String getDigit() {
        return digit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_system_code_item.digit
     *
     * @param digit the value for tr_system_code_item.digit
     *
     * @mbggenerated
     */
    public void setDigit(String digit) {
        this.digit = digit == null ? null : digit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_system_code_item.creator
     *
     * @return the value of tr_system_code_item.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_system_code_item.creator
     *
     * @param creator the value for tr_system_code_item.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_system_code_item.createtime
     *
     * @return the value of tr_system_code_item.createtime
     *
     * @mbggenerated
     */
    public Long getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_system_code_item.createtime
     *
     * @param createtime the value for tr_system_code_item.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Long createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_system_code_item.modifier
     *
     * @return the value of tr_system_code_item.modifier
     *
     * @mbggenerated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_system_code_item.modifier
     *
     * @param modifier the value for tr_system_code_item.modifier
     *
     * @mbggenerated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_system_code_item.modifytime
     *
     * @return the value of tr_system_code_item.modifytime
     *
     * @mbggenerated
     */
    public Long getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_system_code_item.modifytime
     *
     * @param modifytime the value for tr_system_code_item.modifytime
     *
     * @mbggenerated
     */
    public void setModifytime(Long modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_system_code_item.utc
     *
     * @return the value of tr_system_code_item.utc
     *
     * @mbggenerated
     */
    public Date getUtc() {
        return utc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_system_code_item.utc
     *
     * @param utc the value for tr_system_code_item.utc
     *
     * @mbggenerated
     */
    public void setUtc(Date utc) {
        this.utc = utc;
    }
}