package com.tianrui.api.req.basicFile.other;

import com.tianrui.api.req.BaseReq;

public class OtherBdSupplierReq extends BaseReq {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6566507253635548749L;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tr_other_bd_supplier.id
	 * @mbggenerated
	 * 主键id
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tr_other_bd_supplier.code
	 * @mbggenerated
	 * 编码
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tr_other_bd_supplier.innercode
	 * @mbggenerated
	 * 内码
	 */
	private String innercode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tr_other_bd_supplier.name
	 * @mbggenerated
	 * 名称
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tr_other_bd_supplier.info
	 * @mbggenerated
	 * 简称
	 */
	private String info;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tr_other_bd_supplier.isvalid
	 * @mbggenerated
	 * 有效性(默认无效   0 无效   1有效)
	 */
	private Byte isvalid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tr_other_bd_supplier.orgid
	 * @mbggenerated
	 * 组织id
	 */
	private String orgid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tr_other_bd_supplier.orgname
	 * @mbggenerated
	 * 组织名称
	 */
	private String orgname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tr_other_bd_supplier.remark
	 * @mbggenerated
	 * 备注
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tr_other_bd_supplier.creator
	 * @mbggenerated
	 * 用户名称
	 */
	private String userName;
	/**
	 * 页码
	 */
	private Integer pageNo;
	/**
	 * 每页显示的条数
	 */
	private Integer pageSize;
	/**
	 * 查询开始位置
	 */
	private Integer start;
	/**
	 * 名字模糊查询
	 */
	private String nameLike;
	/**
	 * 内码模糊查询
	 */
	private String innercodeLike;
	
	
	public String getNameLike() {
		return nameLike;
	}
	public void setNameLike(String nameLike) {
		this.nameLike = nameLike;
	}
	public String getInnercodeLike() {
		return innercodeLike;
	}
	public void setInnercodeLike(String innercodeLike) {
		this.innercodeLike = innercodeLike;
	}
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getCode() {
		return code;
	}
	public void setCode(String code) {
		this.code = code;
	}
	public String getInnercode() {
		return innercode;
	}
	public void setInnercode(String innercode) {
		this.innercode = innercode;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getInfo() {
		return info;
	}
	public void setInfo(String info) {
		this.info = info;
	}
	public Byte getIsvalid() {
		return isvalid;
	}
	public void setIsvalid(Byte isvalid) {
		this.isvalid = isvalid;
	}
	public String getOrgid() {
		return orgid;
	}
	public void setOrgid(String orgid) {
		this.orgid = orgid;
	}
	public String getOrgname() {
		return orgname;
	}
	public void setOrgname(String orgname) {
		this.orgname = orgname;
	}
	public String getRemark() {
		return remark;
	}
	public void setRemark(String remark) {
		this.remark = remark;
	}
	public String getUserName() {
		return userName;
	}
	public void setUserName(String userName) {
		this.userName = userName;
	}
	public Integer getPageNo() {
		return pageNo;
	}
	public void setPageNo(Integer pageNo) {
		this.pageNo = pageNo;
	}
	public Integer getPageSize() {
		return pageSize;
	}
	public void setPageSize(Integer pageSize) {
		this.pageSize = pageSize;
	}
	public Integer getStart() {
		return start;
	}
	public void setStart(Integer start) {
		this.start = start;
	}
	
}
