package com.tianrui.api.resp.system.base;

import java.util.Date;

import com.tianrui.api.resp.BaseResp;

public class SystemCodeResp extends BaseResp {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2868630997607360232L;
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_system_code.id
     *	自定义编号ID
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_system_code.code
     *	单据代号
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_system_code.name
     *	单据名称
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_system_code.key
     *	单据类型
     * @mbggenerated
     */
    private String key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_system_code.example
     *	说明
     * @mbggenerated
     */
    private String example;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_system_code.code_type
     *	编号方式
     * @mbggenerated
     */
    private Byte codeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_system_code.split_type
     *	分割符
     * @mbggenerated
     */
    private Byte splitType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_system_code.code_begin
     *	起始编号
     * @mbggenerated
     */
    private Byte codeBegin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_system_code.inner_code_begin
     *	起始内码
     * @mbggenerated
     */
    private Byte innerCodeBegin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_system_code.creator
     *	创建者
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_system_code.createtime
     *	创建时间
     * @mbggenerated
     */
    private Long createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_system_code.modifier
     *	修改者
     * @mbggenerated
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_system_code.modifytime
     *	修改时间
     * @mbggenerated
     */
    private Long modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_system_code.utc
     *	最近更新时间/版本号
     * @mbggenerated
     */
    private Date utc;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getKey() {
		return key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	public String getExample() {
		return example;
	}

	public void setExample(String example) {
		this.example = example;
	}

	public Byte getCodeType() {
		return codeType;
	}

	public void setCodeType(Byte codeType) {
		this.codeType = codeType;
	}

	public Byte getSplitType() {
		return splitType;
	}

	public void setSplitType(Byte splitType) {
		this.splitType = splitType;
	}

	public Byte getCodeBegin() {
		return codeBegin;
	}

	public void setCodeBegin(Byte codeBegin) {
		this.codeBegin = codeBegin;
	}

	public Byte getInnerCodeBegin() {
		return innerCodeBegin;
	}

	public void setInnerCodeBegin(Byte innerCodeBegin) {
		this.innerCodeBegin = innerCodeBegin;
	}

	public String getCreator() {
		return creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public Long getCreatetime() {
		return createtime;
	}

	public void setCreatetime(Long createtime) {
		this.createtime = createtime;
	}

	public String getModifier() {
		return modifier;
	}

	public void setModifier(String modifier) {
		this.modifier = modifier;
	}

	public Long getModifytime() {
		return modifytime;
	}

	public void setModifytime(Long modifytime) {
		this.modifytime = modifytime;
	}

	public Date getUtc() {
		return utc;
	}

	public void setUtc(Date utc) {
		this.utc = utc;
	}

	
}
