package com.tianrui.service.mapper.basicFile.other;

import java.util.List;

import com.tianrui.api.req.basicFile.other.OtherBdVehicleReq;
import com.tianrui.service.bean.basicFile.other.OtherBdVehicle;

public interface OtherBdVehicleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_other_bd_vehice
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_other_bd_vehice
     *
     * @mbggenerated
     */
    int insert(OtherBdVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_other_bd_vehice
     *
     * @mbggenerated
     */
    int insertSelective(OtherBdVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_other_bd_vehice
     *
     * @mbggenerated
     */
    OtherBdVehicle selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_other_bd_vehice
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OtherBdVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_other_bd_vehice
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OtherBdVehicle record);
    
    
    long findVehiclePageCount(OtherBdVehicleReq req);

	List<OtherBdVehicle> findVehiclePage(OtherBdVehicleReq req);
	
	int findVehicleByName(String name);
}