package com.tianrui.service.mapper.basicFile.other;

import java.util.List;

import com.tianrui.api.req.basicFile.other.OtherBdSupplierReq;
import com.tianrui.service.bean.basicFile.other.OtherBdSupplier;

public interface OtherBdSupplierMapper {

	/**
	 * 删除数据(主键id)
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tr_other_bd_supplier
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * 新增数据
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tr_other_bd_supplier
	 * @mbggenerated
	 */
	int insert(OtherBdSupplier record);

	/**
	 * 新增数据(动态)
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tr_other_bd_supplier
	 * @mbggenerated
	 */
	int insertSelective(OtherBdSupplier record);

	/**
	 * 查询数据(主键id)
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tr_other_bd_supplier
	 * @mbggenerated
	 */
	OtherBdSupplier selectByPrimaryKey(String id);

	/**
	 * 更新数据(动态)
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tr_other_bd_supplier
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(OtherBdSupplier record);

	/**
	 * 更新数据
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tr_other_bd_supplier
	 * @mbggenerated
	 */
	int updateByPrimaryKey(OtherBdSupplier record);
	/**
	 * 查询数据总数
	 */
	int count(OtherBdSupplierReq req);
	/**
	 * 分页查询数据
	 */
	List<OtherBdSupplier> page(OtherBdSupplierReq req);
	
	
}