package com.tianrui.service.mapper.basicFile.other;

import com.tianrui.service.bean.basicFile.other.OtherBdMaterial;

public interface OtherBdMaterialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_other_bd_material
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_other_bd_material
     *
     * @mbggenerated
     */
    int insert(OtherBdMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_other_bd_material
     *
     * @mbggenerated
     */
    int insertSelective(OtherBdMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_other_bd_material
     *
     * @mbggenerated
     */
    OtherBdMaterial selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_other_bd_material
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OtherBdMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_other_bd_material
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OtherBdMaterial record);
}