package com.tianrui.service.mapper.basicFile.other;

import java.util.List;

import com.tianrui.api.req.basicFile.other.OtherBdDriverReq;
import com.tianrui.service.bean.basicFile.other.OtherBdDriver;

public interface OtherBdDriverMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_other_bd_driver
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_other_bd_driver
     *
     * @mbggenerated
     */
    int insert(OtherBdDriver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_other_bd_driver
     *
     * @mbggenerated
     */
    int insertSelective(OtherBdDriver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_other_bd_driver
     *
     * @mbggenerated
     */
    OtherBdDriver selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_other_bd_driver
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OtherBdDriver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_other_bd_driver
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OtherBdDriver record);
    /**
     * 查询分页数据总数
     * @param req
     * @return
     */
    long findDriverPageCount(OtherBdDriverReq req);
    
    /**
     * 分页查询数据
     * @param req
     * @return
     */
	List<OtherBdDriver> findDriverPage(OtherBdDriverReq req);
	
	/**
	 * 根据名称查询数据
	 * @param name
	 * @return
	 */
	int findDriverByName(String name);
}