package com.tianrui.service.mapper.basicFile.other;

import java.util.List;

import com.tianrui.api.req.basicFile.other.OtherBdCustomerReq;
import com.tianrui.service.bean.basicFile.other.OtherBdCustomer;

public interface OtherBdCustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_other_bd_customer
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_other_bd_customer
     *
     * @mbggenerated
     */
    int insert(OtherBdCustomerReq req);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_other_bd_customer
     *
     * @mbggenerated
     */
    int insertSelective(OtherBdCustomerReq req);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_other_bd_customer
     *
     * @mbggenerated
     */
    OtherBdCustomer selectByPrimaryKey(String id);
    /**
     * 分页查询
     * @param 查询信息
     * @return List<OtherBdCustomer>
     */
    List<OtherBdCustomer> page(OtherBdCustomerReq req);
    /**
     * 查询数据总数
     * @return int
     */
    int count(OtherBdCustomerReq req);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_other_bd_customer
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OtherBdCustomerReq req);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_other_bd_customer
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OtherBdCustomerReq req);

	int findCustomerByName(String name);
}