package com.tianrui.service.mapper.basicFile.other;

import com.tianrui.service.bean.basicFile.other.OtherBdDriver;

public interface OtherBdDriverMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_other_bd_driver
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_other_bd_driver
     *
     * @mbggenerated
     */
    int insert(OtherBdDriver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_other_bd_driver
     *
     * @mbggenerated
     */
    int insertSelective(OtherBdDriver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_other_bd_driver
     *
     * @mbggenerated
     */
    OtherBdDriver selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_other_bd_driver
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OtherBdDriver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_other_bd_driver
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OtherBdDriver record);
}