package com.tianrui.service.mapper.basicFile.other;

import java.util.List;

import com.tianrui.api.req.basicFile.other.OtherBdCustomerReq;
import com.tianrui.service.bean.basicFile.other.OtherBdCustomer;

public interface OtherBdCustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_other_bd_customer
     *	通过主键ID删除数据
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_other_bd_customer
     *	新增数据(整体)
     * @mbggenerated
     */
    int insert(OtherBdCustomer tomer);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_other_bd_customer
     *	新增数据(动态)
     * @mbggenerated
     */
    int insertSelective(OtherBdCustomer tomer);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_other_bd_customer
     *	通过主键ID查找数据
     * @mbggenerated
     */
    OtherBdCustomer selectByPrimaryKey(String id);
    /**
     * 分页查询
     * @param 查询信息
     * @return List<OtherBdCustomer>
     */
    List<OtherBdCustomer> page(OtherBdCustomerReq req);
    /**
     * 查询数据总数
     * @return int
     */
    int count(OtherBdCustomerReq req);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_other_bd_customer
     *	更新数据(动态)
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OtherBdCustomer tomer);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_other_bd_customer
     *	更新数据(整体)
     * @mbggenerated
     */
    int updateByPrimaryKey(OtherBdCustomer tomer);

}