package com.tianrui.service.bean.common;

public class RFID {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_RFID.RFID
     *
     * @mbggenerated
     */
    private String rfid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_RFID.state
     *
     * @mbggenerated
     */
    private Boolean state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_RFID.source
     *
     * @mbggenerated
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_RFID.desc
     *
     * @mbggenerated
     */
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_RFID.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_RFID.createtime
     *
     * @mbggenerated
     */
    private Long createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_RFID.modifier
     *
     * @mbggenerated
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_RFID.modifytime
     *
     * @mbggenerated
     */
    private Long modifytime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_RFID.RFID
     *
     * @return the value of tr_RFID.RFID
     *
     * @mbggenerated
     */
    public String getRfid() {
        return rfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_RFID.RFID
     *
     * @param rfid the value for tr_RFID.RFID
     *
     * @mbggenerated
     */
    public void setRfid(String rfid) {
        this.rfid = rfid == null ? null : rfid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_RFID.state
     *
     * @return the value of tr_RFID.state
     *
     * @mbggenerated
     */
    public Boolean getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_RFID.state
     *
     * @param state the value for tr_RFID.state
     *
     * @mbggenerated
     */
    public void setState(Boolean state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_RFID.source
     *
     * @return the value of tr_RFID.source
     *
     * @mbggenerated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_RFID.source
     *
     * @param source the value for tr_RFID.source
     *
     * @mbggenerated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }
    public String getInfo() {
		return info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_RFID.creator
     *
     * @return the value of tr_RFID.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_RFID.creator
     *
     * @param creator the value for tr_RFID.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_RFID.createtime
     *
     * @return the value of tr_RFID.createtime
     *
     * @mbggenerated
     */
    public Long getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_RFID.createtime
     *
     * @param createtime the value for tr_RFID.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Long createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_RFID.modifier
     *
     * @return the value of tr_RFID.modifier
     *
     * @mbggenerated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_RFID.modifier
     *
     * @param modifier the value for tr_RFID.modifier
     *
     * @mbggenerated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_RFID.modifytime
     *
     * @return the value of tr_RFID.modifytime
     *
     * @mbggenerated
     */
    public Long getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_RFID.modifytime
     *
     * @param modifytime the value for tr_RFID.modifytime
     *
     * @mbggenerated
     */
    public void setModifytime(Long modifytime) {
        this.modifytime = modifytime;
    }
}