package com.tianrui.api.resp.basicFile.other;

import com.tianrui.api.resp.BaseResp;

public class OtherBdSupplierResp extends BaseResp {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7155468475230565938L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tr_other_bd_supplier.id
	 * @mbggenerated
	 * 主键id
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tr_other_bd_supplier.code
	 * @mbggenerated
	 * 编码
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tr_other_bd_supplier.innercode
	 * @mbggenerated
	 * 内码
	 */
	private String innercode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tr_other_bd_supplier.name
	 * @mbggenerated
	 * 名称
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tr_other_bd_supplier.info
	 * @mbggenerated
	 * 简称
	 */
	private String info;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tr_other_bd_supplier.isvalid
	 * @mbggenerated
	 * 有效性(默认无效   0 无效   1有效)
	 */
	private Byte isvalid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tr_other_bd_supplier.orgid
	 * @mbggenerated
	 * 组织id
	 */
	private String orgid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tr_other_bd_supplier.orgname
	 * @mbggenerated
	 * 组织名称
	 */
	private String orgname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tr_other_bd_supplier.remark
	 * @mbggenerated
	 * 备注
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tr_other_bd_supplier.creator
	 * @mbggenerated
	 * 创建人
	 */
	private String creator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tr_other_bd_supplier.createtime
	 * @mbggenerated
	 * 创建时间
	 */
	private Long createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tr_other_bd_supplier.modifier
	 * @mbggenerated
	 * 修改者
	 */
	private String modifier;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tr_other_bd_supplier.modifytime
	 * @mbggenerated
	 * 修改时间
	 */
	private Long modifytime;
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getCode() {
		return code;
	}
	public void setCode(String code) {
		this.code = code;
	}
	public String getInnercode() {
		return innercode;
	}
	public void setInnercode(String innercode) {
		this.innercode = innercode;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getInfo() {
		return info;
	}
	public void setInfo(String info) {
		this.info = info;
	}
	public Byte getIsvalid() {
		return isvalid;
	}
	public void setIsvalid(Byte isvalid) {
		this.isvalid = isvalid;
	}
	public String getOrgid() {
		return orgid;
	}
	public void setOrgid(String orgid) {
		this.orgid = orgid;
	}
	public String getOrgname() {
		return orgname;
	}
	public void setOrgname(String orgname) {
		this.orgname = orgname;
	}
	public String getRemark() {
		return remark;
	}
	public void setRemark(String remark) {
		this.remark = remark;
	}
	public String getCreator() {
		return creator;
	}
	public void setCreator(String creator) {
		this.creator = creator;
	}
	public Long getCreatetime() {
		return createtime;
	}
	public void setCreatetime(Long createtime) {
		this.createtime = createtime;
	}
	public String getModifier() {
		return modifier;
	}
	public void setModifier(String modifier) {
		this.modifier = modifier;
	}
	public Long getModifytime() {
		return modifytime;
	}
	public void setModifytime(Long modifytime) {
		this.modifytime = modifytime;
	}


	
}
