package com.tianrui.service.mapper.system.base;


import com.tianrui.api.req.system.base.SystemCodeReq;
import com.tianrui.service.bean.system.base.SystemCodeItem;

public interface SystemCodeItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_system_code_item
     *	删除数据
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_system_code_item
     *	新增数据
     * @mbggenerated
     */
    int insert(SystemCodeItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_system_code_item
     *	新增数据(动态)
     * @mbggenerated
     */
    int insertSelective(SystemCodeItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_system_code_item
     *	通过主键查询数据
     * @mbggenerated
     */
    SystemCodeItem selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_system_code_item
     *	更新数据(动态)
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemCodeItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_system_code_item
     *	更新数据
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemCodeItem record);
    /**
     * 查询数据(通过req)
     */
    SystemCodeItem selectByReq(SystemCodeReq req);
}