package com.tianrui.service.mapper.system.base;

import com.tianrui.service.bean.system.base.SystemCodeItem;

public interface SystemCodeItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_system_code_item
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_system_code_item
     *
     * @mbggenerated
     */
    int insert(SystemCodeItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_system_code_item
     *
     * @mbggenerated
     */
    int insertSelective(SystemCodeItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_system_code_item
     *
     * @mbggenerated
     */
    SystemCodeItem selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_system_code_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemCodeItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_system_code_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemCodeItem record);
}