package com.tianrui.service.mapper.system.base;

import java.util.List;

import com.tianrui.api.req.system.base.SystemCodeReq;
import com.tianrui.service.bean.system.base.SystemCode;

public interface SystemCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_system_code
     *	删除数据
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_system_code
     *	新增数据
     * @mbggenerated
     */
    int insert(SystemCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_system_code
     *	新增数据(动态)
     * @mbggenerated
     */
    int insertSelective(SystemCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_system_code
     *	查询数据(通过主键ID)
     * @mbggenerated
     */
    SystemCode selectByPrimaryKey(String id);
    SystemCode selectByCode(String code);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_system_code
     *	更新数据(动态)
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_system_code
     *	更新数据
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemCode record);
    /**
     * 查询数据(动态),用于分页查询等
     * @param req
     * @return List集合
     */
    List<SystemCode> selectByReq(SystemCodeReq req);
    
}