package com.tianrui.service.mapper.system.base;

import com.tianrui.service.bean.system.base.SystemDataDictItem;

public interface SystemDataDictItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_system_data_dict_item
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_system_data_dict_item
     *
     * @mbggenerated
     */
    int insert(SystemDataDictItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_system_data_dict_item
     *
     * @mbggenerated
     */
    int insertSelective(SystemDataDictItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_system_data_dict_item
     *
     * @mbggenerated
     */
    SystemDataDictItem selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_system_data_dict_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemDataDictItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_system_data_dict_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemDataDictItem record);
}