package com.tianrui.service.bean.system.auth;

import java.util.Date;

public class SystemMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_system_menu.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_system_menu.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_system_menu.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_system_menu.role_type
     *
     * @mbggenerated
     */
    private String roleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_system_menu.isvalid
     *
     * @mbggenerated
     */
    private Byte isvalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_system_menu.uri
     *
     * @mbggenerated
     */
    private String uri;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_system_menu.order_by
     *
     * @mbggenerated
     */
    private Integer orderBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_system_menu.deep
     *
     * @mbggenerated
     */
    private Integer deep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_system_menu.param
     *
     * @mbggenerated
     */
    private String param;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_system_menu.img_type
     *
     * @mbggenerated
     */
    private Byte imgType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_system_menu.info
     *
     * @mbggenerated
     */
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_system_menu.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_system_menu.createtime
     *
     * @mbggenerated
     */
    private Long createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_system_menu.modifier
     *
     * @mbggenerated
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_system_menu.modifytime
     *
     * @mbggenerated
     */
    private Long modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_system_menu.utc
     *
     * @mbggenerated
     */
    private Date utc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_system_menu.id
     *
     * @return the value of tr_system_menu.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_system_menu.id
     *
     * @param id the value for tr_system_menu.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_system_menu.code
     *
     * @return the value of tr_system_menu.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_system_menu.code
     *
     * @param code the value for tr_system_menu.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_system_menu.name
     *
     * @return the value of tr_system_menu.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_system_menu.name
     *
     * @param name the value for tr_system_menu.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_system_menu.role_type
     *
     * @return the value of tr_system_menu.role_type
     *
     * @mbggenerated
     */
    public String getRoleType() {
        return roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_system_menu.role_type
     *
     * @param roleType the value for tr_system_menu.role_type
     *
     * @mbggenerated
     */
    public void setRoleType(String roleType) {
        this.roleType = roleType == null ? null : roleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_system_menu.isvalid
     *
     * @return the value of tr_system_menu.isvalid
     *
     * @mbggenerated
     */
    public Byte getIsvalid() {
        return isvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_system_menu.isvalid
     *
     * @param isvalid the value for tr_system_menu.isvalid
     *
     * @mbggenerated
     */
    public void setIsvalid(Byte isvalid) {
        this.isvalid = isvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_system_menu.uri
     *
     * @return the value of tr_system_menu.uri
     *
     * @mbggenerated
     */
    public String getUri() {
        return uri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_system_menu.uri
     *
     * @param uri the value for tr_system_menu.uri
     *
     * @mbggenerated
     */
    public void setUri(String uri) {
        this.uri = uri == null ? null : uri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_system_menu.order_by
     *
     * @return the value of tr_system_menu.order_by
     *
     * @mbggenerated
     */
    public Integer getOrderBy() {
        return orderBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_system_menu.order_by
     *
     * @param orderBy the value for tr_system_menu.order_by
     *
     * @mbggenerated
     */
    public void setOrderBy(Integer orderBy) {
        this.orderBy = orderBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_system_menu.deep
     *
     * @return the value of tr_system_menu.deep
     *
     * @mbggenerated
     */
    public Integer getDeep() {
        return deep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_system_menu.deep
     *
     * @param deep the value for tr_system_menu.deep
     *
     * @mbggenerated
     */
    public void setDeep(Integer deep) {
        this.deep = deep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_system_menu.param
     *
     * @return the value of tr_system_menu.param
     *
     * @mbggenerated
     */
    public String getParam() {
        return param;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_system_menu.param
     *
     * @param param the value for tr_system_menu.param
     *
     * @mbggenerated
     */
    public void setParam(String param) {
        this.param = param == null ? null : param.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_system_menu.img_type
     *
     * @return the value of tr_system_menu.img_type
     *
     * @mbggenerated
     */
    public Byte getImgType() {
        return imgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_system_menu.img_type
     *
     * @param imgType the value for tr_system_menu.img_type
     *
     * @mbggenerated
     */
    public void setImgType(Byte imgType) {
        this.imgType = imgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_system_menu.info
     *
     * @return the value of tr_system_menu.info
     *
     * @mbggenerated
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_system_menu.info
     *
     * @param info the value for tr_system_menu.info
     *
     * @mbggenerated
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_system_menu.creator
     *
     * @return the value of tr_system_menu.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_system_menu.creator
     *
     * @param creator the value for tr_system_menu.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_system_menu.createtime
     *
     * @return the value of tr_system_menu.createtime
     *
     * @mbggenerated
     */
    public Long getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_system_menu.createtime
     *
     * @param createtime the value for tr_system_menu.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Long createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_system_menu.modifier
     *
     * @return the value of tr_system_menu.modifier
     *
     * @mbggenerated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_system_menu.modifier
     *
     * @param modifier the value for tr_system_menu.modifier
     *
     * @mbggenerated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_system_menu.modifytime
     *
     * @return the value of tr_system_menu.modifytime
     *
     * @mbggenerated
     */
    public Long getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_system_menu.modifytime
     *
     * @param modifytime the value for tr_system_menu.modifytime
     *
     * @mbggenerated
     */
    public void setModifytime(Long modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_system_menu.utc
     *
     * @return the value of tr_system_menu.utc
     *
     * @mbggenerated
     */
    public Date getUtc() {
        return utc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_system_menu.utc
     *
     * @param utc the value for tr_system_menu.utc
     *
     * @mbggenerated
     */
    public void setUtc(Date utc) {
        this.utc = utc;
    }
}