package com.tianrui.service.bean.system.auth;

import java.util.Date;
/**
 * @description 菜单管理实体bean
 * @author YangZhenFu
 * @createtime 2017年3月27日 上午9:17:07
 */
public class SystemMenu {
   
    private String id;
    //模块编码
    private String code;
    //模块名称
    private String name;
    //上级模块id
    private String roleid;
    //上级模块名称
    private String roleType;
    //有效性    默认无效 0无效 1有效
    private Byte isvalid;
    //链接地址
    private String uri;
    //排序
    private Integer orderBy;
    //深度	
    private Integer deep;
    //参数
    private String param;
    //菜单图片
    private Byte imgType;
    //说明
    private String info;
    //连接目标
    private String linkgoal;
    //分组行
    private Integer grouping;
    //创建人
    private String creator;
    //创建时间
    private Long createtime;
    //最后修改人
    private String modifier;
    //最后修改时间
    private Long modifytime;
    //时间戳
    private Date utc;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_system_menu.code
     *
     * @param code the value for tr_system_menu.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_system_menu.name
     *
     * @return the value of tr_system_menu.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_system_menu.name
     *
     * @param name the value for tr_system_menu.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_system_menu.role_type
     *
     * @return the value of tr_system_menu.role_type
     *
     * @mbggenerated
     */
    public String getRoleType() {
        return roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_system_menu.role_type
     *
     * @param roleType the value for tr_system_menu.role_type
     *
     * @mbggenerated
     */
    public void setRoleType(String roleType) {
        this.roleType = roleType == null ? null : roleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_system_menu.isvalid
     *
     * @return the value of tr_system_menu.isvalid
     *
     * @mbggenerated
     */
    public Byte getIsvalid() {
        return isvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_system_menu.isvalid
     *
     * @param isvalid the value for tr_system_menu.isvalid
     *
     * @mbggenerated
     */
    public void setIsvalid(Byte isvalid) {
        this.isvalid = isvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_system_menu.uri
     *
     * @return the value of tr_system_menu.uri
     *
     * @mbggenerated
     */
    public String getUri() {
        return uri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_system_menu.uri
     *
     * @param uri the value for tr_system_menu.uri
     *
     * @mbggenerated
     */
    public void setUri(String uri) {
        this.uri = uri == null ? null : uri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_system_menu.order_by
     *
     * @return the value of tr_system_menu.order_by
     *
     * @mbggenerated
     */
    public Integer getOrderBy() {
        return orderBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_system_menu.order_by
     *
     * @param orderBy the value for tr_system_menu.order_by
     *
     * @mbggenerated
     */
    public void setOrderBy(Integer orderBy) {
        this.orderBy = orderBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_system_menu.deep
     *
     * @return the value of tr_system_menu.deep
     *
     * @mbggenerated
     */
    public Integer getDeep() {
        return deep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_system_menu.deep
     *
     * @param deep the value for tr_system_menu.deep
     *
     * @mbggenerated
     */
    public void setDeep(Integer deep) {
        this.deep = deep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_system_menu.param
     *
     * @return the value of tr_system_menu.param
     *
     * @mbggenerated
     */
    public String getParam() {
        return param;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_system_menu.param
     *
     * @param param the value for tr_system_menu.param
     *
     * @mbggenerated
     */
    public void setParam(String param) {
        this.param = param == null ? null : param.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_system_menu.img_type
     *
     * @return the value of tr_system_menu.img_type
     *
     * @mbggenerated
     */
    public Byte getImgType() {
        return imgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_system_menu.img_type
     *
     * @param imgType the value for tr_system_menu.img_type
     *
     * @mbggenerated
     */
    public void setImgType(Byte imgType) {
        this.imgType = imgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_system_menu.info
     *
     * @return the value of tr_system_menu.info
     *
     * @mbggenerated
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_system_menu.info
     *
     * @param info the value for tr_system_menu.info
     *
     * @mbggenerated
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_system_menu.creator
     *
     * @return the value of tr_system_menu.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_system_menu.creator
     *
     * @param creator the value for tr_system_menu.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_system_menu.createtime
     *
     * @return the value of tr_system_menu.createtime
     *
     * @mbggenerated
     */
    public Long getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_system_menu.createtime
     *
     * @param createtime the value for tr_system_menu.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Long createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_system_menu.modifier
     *
     * @return the value of tr_system_menu.modifier
     *
     * @mbggenerated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_system_menu.modifier
     *
     * @param modifier the value for tr_system_menu.modifier
     *
     * @mbggenerated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_system_menu.modifytime
     *
     * @return the value of tr_system_menu.modifytime
     *
     * @mbggenerated
     */
    public Long getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_system_menu.modifytime
     *
     * @param modifytime the value for tr_system_menu.modifytime
     *
     * @mbggenerated
     */
    public void setModifytime(Long modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_system_menu.utc
     *
     * @return the value of tr_system_menu.utc
     *
     * @mbggenerated
     */
    public Date getUtc() {
        return utc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_system_menu.utc
     *
     * @param utc the value for tr_system_menu.utc
     *
     * @mbggenerated
     */
    public void setUtc(Date utc) {
        this.utc = utc;
    }

	public String getLinkgoal() {
		return linkgoal;
	}

	public void setLinkgoal(String linkgoal) {
		this.linkgoal = linkgoal;
	}

	public Integer getGrouping() {
		return grouping;
	}

	public void setGrouping(Integer grouping) {
		this.grouping = grouping;
	}

	public String getRoleid() {
		return roleid;
	}

	public void setRoleid(String roleid) {
		this.roleid = roleid;
	}


    
}