package com.tianrui.test.api.web;

import java.util.Date;

public class LocalBdStordoc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_stordoc.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_stordoc.org_id
     *
     * @mbggenerated
     */
    private String orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_stordoc.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_stordoc.short_name
     *
     * @mbggenerated
     */
    private String shortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_stordoc.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_stordoc.inner_code
     *
     * @mbggenerated
     */
    private String innerCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_stordoc.ts
     *
     * @mbggenerated
     */
    private Date ts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_stordoc.is_push
     *
     * @mbggenerated
     */
    private Byte isPush;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_stordoc.push_time
     *
     * @mbggenerated
     */
    private Long pushTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_stordoc.create_time
     *
     * @mbggenerated
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_stordoc.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_stordoc.id
     *
     * @return the value of bd_stordoc.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_stordoc.id
     *
     * @param id the value for bd_stordoc.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_stordoc.org_id
     *
     * @return the value of bd_stordoc.org_id
     *
     * @mbggenerated
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_stordoc.org_id
     *
     * @param orgId the value for bd_stordoc.org_id
     *
     * @mbggenerated
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_stordoc.name
     *
     * @return the value of bd_stordoc.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_stordoc.name
     *
     * @param name the value for bd_stordoc.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_stordoc.short_name
     *
     * @return the value of bd_stordoc.short_name
     *
     * @mbggenerated
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_stordoc.short_name
     *
     * @param shortName the value for bd_stordoc.short_name
     *
     * @mbggenerated
     */
    public void setShortName(String shortName) {
        this.shortName = shortName == null ? null : shortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_stordoc.code
     *
     * @return the value of bd_stordoc.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_stordoc.code
     *
     * @param code the value for bd_stordoc.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_stordoc.inner_code
     *
     * @return the value of bd_stordoc.inner_code
     *
     * @mbggenerated
     */
    public String getInnerCode() {
        return innerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_stordoc.inner_code
     *
     * @param innerCode the value for bd_stordoc.inner_code
     *
     * @mbggenerated
     */
    public void setInnerCode(String innerCode) {
        this.innerCode = innerCode == null ? null : innerCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_stordoc.ts
     *
     * @return the value of bd_stordoc.ts
     *
     * @mbggenerated
     */
    public Date getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_stordoc.ts
     *
     * @param ts the value for bd_stordoc.ts
     *
     * @mbggenerated
     */
    public void setTs(Date ts) {
        this.ts = ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_stordoc.is_push
     *
     * @return the value of bd_stordoc.is_push
     *
     * @mbggenerated
     */
    public Byte getIsPush() {
        return isPush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_stordoc.is_push
     *
     * @param isPush the value for bd_stordoc.is_push
     *
     * @mbggenerated
     */
    public void setIsPush(Byte isPush) {
        this.isPush = isPush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_stordoc.push_time
     *
     * @return the value of bd_stordoc.push_time
     *
     * @mbggenerated
     */
    public Long getPushTime() {
        return pushTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_stordoc.push_time
     *
     * @param pushTime the value for bd_stordoc.push_time
     *
     * @mbggenerated
     */
    public void setPushTime(Long pushTime) {
        this.pushTime = pushTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_stordoc.create_time
     *
     * @return the value of bd_stordoc.create_time
     *
     * @mbggenerated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_stordoc.create_time
     *
     * @param createTime the value for bd_stordoc.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_stordoc.remark
     *
     * @return the value of bd_stordoc.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_stordoc.remark
     *
     * @param remark the value for bd_stordoc.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}