package com.tianrui.service.bean.basicFile.other;

public class OtherBdSupplier {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tr_other_bd_supplier.id
	 * @mbggenerated
	 * 主键id
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tr_other_bd_supplier.code
	 * @mbggenerated
	 * 编码
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tr_other_bd_supplier.innercode
	 * @mbggenerated
	 * 内码
	 */
	private String innercode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tr_other_bd_supplier.name
	 * @mbggenerated
	 * 名称
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tr_other_bd_supplier.info
	 * @mbggenerated
	 * 简称
	 */
	private String info;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tr_other_bd_supplier.isvalid
	 * @mbggenerated
	 * 有效性(默认无效   0 无效   1有效)
	 */
	private Byte isvalid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tr_other_bd_supplier.orgid
	 * @mbggenerated
	 * 组织id
	 */
	private String orgid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tr_other_bd_supplier.orgname
	 * @mbggenerated
	 * 组织名称
	 */
	private String orgname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tr_other_bd_supplier.remark
	 * @mbggenerated
	 * 备注
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tr_other_bd_supplier.creator
	 * @mbggenerated
	 * 创建人
	 */
	private String creator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tr_other_bd_supplier.createtime
	 * @mbggenerated
	 * 创建时间
	 */
	private Long createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tr_other_bd_supplier.modifier
	 * @mbggenerated
	 * 修改者
	 */
	private String modifier;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tr_other_bd_supplier.modifytime
	 * @mbggenerated
	 * 修改时间
	 */
	private Long modifytime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tr_other_bd_supplier.id
	 * @return  the value of tr_other_bd_supplier.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tr_other_bd_supplier.id
	 * @param id  the value for tr_other_bd_supplier.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tr_other_bd_supplier.code
	 * @return  the value of tr_other_bd_supplier.code
	 * @mbggenerated
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tr_other_bd_supplier.code
	 * @param code  the value for tr_other_bd_supplier.code
	 * @mbggenerated
	 */
	public void setCode(String code) {
		this.code = code == null ? null : code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tr_other_bd_supplier.innercode
	 * @return  the value of tr_other_bd_supplier.innercode
	 * @mbggenerated
	 */
	public String getInnercode() {
		return innercode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tr_other_bd_supplier.innercode
	 * @param innercode  the value for tr_other_bd_supplier.innercode
	 * @mbggenerated
	 */
	public void setInnercode(String innercode) {
		this.innercode = innercode == null ? null : innercode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tr_other_bd_supplier.name
	 * @return  the value of tr_other_bd_supplier.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tr_other_bd_supplier.name
	 * @param name  the value for tr_other_bd_supplier.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tr_other_bd_supplier.info
	 * @return  the value of tr_other_bd_supplier.info
	 * @mbggenerated
	 */
	public String getInfo() {
		return info;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tr_other_bd_supplier.info
	 * @param info  the value for tr_other_bd_supplier.info
	 * @mbggenerated
	 */
	public void setInfo(String info) {
		this.info = info == null ? null : info.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tr_other_bd_supplier.isvalid
	 * @return  the value of tr_other_bd_supplier.isvalid
	 * @mbggenerated
	 */
	public Byte getIsvalid() {
		return isvalid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tr_other_bd_supplier.isvalid
	 * @param isvalid  the value for tr_other_bd_supplier.isvalid
	 * @mbggenerated
	 */
	public void setIsvalid(Byte isvalid) {
		this.isvalid = isvalid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tr_other_bd_supplier.orgid
	 * @return  the value of tr_other_bd_supplier.orgid
	 * @mbggenerated
	 */
	public String getOrgid() {
		return orgid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tr_other_bd_supplier.orgid
	 * @param orgid  the value for tr_other_bd_supplier.orgid
	 * @mbggenerated
	 */
	public void setOrgid(String orgid) {
		this.orgid = orgid == null ? null : orgid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tr_other_bd_supplier.orgname
	 * @return  the value of tr_other_bd_supplier.orgname
	 * @mbggenerated
	 */
	public String getOrgname() {
		return orgname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tr_other_bd_supplier.orgname
	 * @param orgname  the value for tr_other_bd_supplier.orgname
	 * @mbggenerated
	 */
	public void setOrgname(String orgname) {
		this.orgname = orgname == null ? null : orgname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tr_other_bd_supplier.remark
	 * @return  the value of tr_other_bd_supplier.remark
	 * @mbggenerated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tr_other_bd_supplier.remark
	 * @param remark  the value for tr_other_bd_supplier.remark
	 * @mbggenerated
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tr_other_bd_supplier.creator
	 * @return  the value of tr_other_bd_supplier.creator
	 * @mbggenerated
	 */
	public String getCreator() {
		return creator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tr_other_bd_supplier.creator
	 * @param creator  the value for tr_other_bd_supplier.creator
	 * @mbggenerated
	 */
	public void setCreator(String creator) {
		this.creator = creator == null ? null : creator.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tr_other_bd_supplier.createtime
	 * @return  the value of tr_other_bd_supplier.createtime
	 * @mbggenerated
	 */
	public Long getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tr_other_bd_supplier.createtime
	 * @param createtime  the value for tr_other_bd_supplier.createtime
	 * @mbggenerated
	 */
	public void setCreatetime(Long createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tr_other_bd_supplier.modifier
	 * @return  the value of tr_other_bd_supplier.modifier
	 * @mbggenerated
	 */
	public String getModifier() {
		return modifier;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tr_other_bd_supplier.modifier
	 * @param modifier  the value for tr_other_bd_supplier.modifier
	 * @mbggenerated
	 */
	public void setModifier(String modifier) {
		this.modifier = modifier == null ? null : modifier.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tr_other_bd_supplier.modifytime
	 * @return  the value of tr_other_bd_supplier.modifytime
	 * @mbggenerated
	 */
	public Long getModifytime() {
		return modifytime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tr_other_bd_supplier.modifytime
	 * @param modifytime  the value for tr_other_bd_supplier.modifytime
	 * @mbggenerated
	 */
	public void setModifytime(Long modifytime) {
		this.modifytime = modifytime;
	}
}