package com.tianrui.service.mapper;

import java.util.List;

import com.tianrui.service.bean.demo.Demo;


public interface DemoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuliu_bill
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuliu_bill
     *
     * @mbggenerated
     */
    int insert(Demo record);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuliu_bill
     *
     * @mbggenerated
     */
    int insertSelective(Demo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuliu_bill
     *
     * @mbggenerated
     */
    Demo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuliu_bill
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Demo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuliu_bill
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Demo record);
    
    
    List<Demo> selectByCondition(Demo record);
    
    long countByCondition(Demo record);
    
    Double querySumWithPlan(Demo record);
    
}