package com.tianrui.service.mapper.system.auth;

import com.tianrui.service.bean.system.auth.SystemMenu;

public interface SystemMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_system_menu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_system_menu
     *
     * @mbggenerated
     */
    int insert(SystemMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_system_menu
     *
     * @mbggenerated
     */
    int insertSelective(SystemMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_system_menu
     *
     * @mbggenerated
     */
    SystemMenu selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_system_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_system_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemMenu record);
}