package com.tianrui.service.mapper.system.auth;

import com.tianrui.service.bean.system.auth.SystemUser;

public interface SystemUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_system_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_system_user
     *
     * @mbggenerated
     */
    int insert(SystemUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_system_user
     *
     * @mbggenerated
     */
    int insertSelective(SystemUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_system_user
     *
     * @mbggenerated
     */
    SystemUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_system_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_system_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemUser record);
}