package com.tianrui.service.mapper.system.auth;

import com.tianrui.service.bean.system.auth.SystemRole;

public interface SystemRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_system_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_system_role
     *
     * @mbggenerated
     */
    int insert(SystemRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_system_role
     *
     * @mbggenerated
     */
    int insertSelective(SystemRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_system_role
     *
     * @mbggenerated
     */
    SystemRole selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_system_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_system_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemRole record);
}