package com.tianrui.service.mapper.common;

import com.tianrui.service.bean.common.RFID;

public interface RFIDMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_RFID
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String rfid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_RFID
     *
     * @mbggenerated
     */
    int insert(RFID record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_RFID
     *
     * @mbggenerated
     */
    int insertSelective(RFID record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_RFID
     *
     * @mbggenerated
     */
    RFID selectByPrimaryKey(String rfid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_RFID
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RFID record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_RFID
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RFID record);
}