package com.tianrui.service.mapper.common;

import java.util.List;

import com.tianrui.service.bean.common.RFID;

public interface RFIDMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_RFID
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String rfid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_RFID
     *
     * @mbggenerated
     */
    int insert(RFID record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_RFID
     *
     * @mbggenerated
     */
    int insertSelective(RFID record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_RFID
     *
     * @mbggenerated
     */
    RFID selectByPrimaryKey(String rfid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_RFID
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RFID record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_RFID
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RFID record);
    
    long selectSelectiveCount(RFID record);
    
    List<RFID> selectSelective(RFID record);
    /**
     * @Description 验证RFID是否已注册
     * @author zhanggaohao
     * @version 2017年3月2日 上午9:36:30
     * @param rfid
     * @return
     */
	RFID validateRFID(String rfid);
}